# Generated by Django 4.1.7 on 2023-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(blank=True, null=True, verbose_name='окончание продаж'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='salePrice',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='цена по скидке'),
        ),
    ]
