# Generated by Django 4.1.7 on 2023-03-26 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_remove_tag_product_tag_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('deliveryType', models.CharField(max_length=128, verbose_name='тип доставки')),
                ('paymentType', models.CharField(max_length=128, verbose_name='тип оплаты')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма заказа')),
                ('status', models.CharField(max_length=128, verbose_name='статус')),
                ('city', models.CharField(max_length=256, verbose_name='город')),
                ('address', models.CharField(max_length=256, verbose_name='адрес')),
                ('products', models.ManyToManyField(related_name='orders', to='products.product', verbose_name='продуты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='пользователь', to=settings.AUTH_USER_MODEL, verbose_name='orders')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
