# Generated by Django 4.1.7 on 2023-03-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=256, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(default='', max_length=128, verbose_name='тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(default='', max_length=128, verbose_name='тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=128, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.profile', verbose_name='пользователь'),
        ),
    ]
