# Generated by Django 4.1.7 on 2023-03-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма заказа'),
        ),
    ]
